
import {
  StyleSheet,
} from 'react-native';
export const styles = StyleSheet.create({
  screen: { flex: 1 },
  header: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
  },
  headerTitle: { fontSize: 18, fontWeight: '700' },
  topIcon: { fontSize: 18 },
  searchRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 12, paddingTop: 12 },
  search: {
    flex: 1,
    backgroundColor: '#f2f2f2',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
  },
  sortBtn: { paddingHorizontal: 10, height: 44, borderRadius: 12, backgroundColor: '#111', alignItems: 'center', justifyContent: 'center' },
  sortText: { color: 'white', fontSize: 12, fontWeight: '700' },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#f3f4f6', marginHorizontal: 6,  },
  chipActive: { backgroundColor: '#111' },
  chipText: { color: '#111',height:20 },
  chipTextActive: { color: 'white', fontWeight: '700' },
  card: { flex: 1, backgroundColor: 'white', borderRadius: 16, overflow: 'hidden', padding: 8 },
  cardImage: { width: '100%', height: 140, borderRadius: 12 },
  heart: { position: 'absolute', right: 12, top: 12, padding: 6, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 999 },
  cardTitle: { marginTop: 8, fontWeight: '700' },
  muted: { color: '#6b7280', marginTop: 2 },
  cardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6 },
  price: { fontWeight: '800' },
  addBtn: { backgroundColor: '#111', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10 },
  addBtnText: { color: 'white', fontWeight: '700' },
  detailImage: { width: '100%', height: 340 },
  detailTitle: { fontSize: 22, fontWeight: '800' },
  sectionLabel: { fontWeight: '700', marginBottom: 6 },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  selector: { paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 999 },
  selectorActive: { backgroundColor: '#111', borderColor: '#111' },
  selectorText: { color: '#111' },
  selectorTextActive: { color: 'white', fontWeight: '700' },
  qtyWrap: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  qtyBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  qtyBtnText: { fontSize: 18, fontWeight: '700' },
  qty: { minWidth: 22, textAlign: 'center', fontWeight: '700' },
  cartItem: { flexDirection: 'row', padding: 12, backgroundColor: 'white', borderRadius: 16, marginBottom: 12, alignItems: 'center' },
  cartImage: { width: 84, height: 84, borderRadius: 12 },
  cartTitle: { fontWeight: '700' },
  summary: { backgroundColor: 'white', padding: 12, borderRadius: 16, marginTop: 8 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 6 },
  rowText: { color: '#111' },
  ctaBtn: { backgroundColor: '#111', height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  ctaBtnText: { color: 'white', fontWeight: '800', fontSize: 16 },
});